#! /bin/bash

source script/help
source script/discover_os
source script/show_solutions
source script/pre_req
source script/remove_old
source script/set_mpi

##

install_req=1
i_dir=" "
sq=0

while getopts :di:shc: FLAG; do
	case $FLAG in
	    d)
	      echo "Disable depencencies installation"
	      install_req=0
	      ;;
	    i)
	      echo "Setting dependencies installation dir: $OPTARG"
	      i_dir=$OPTARG
	      ;;
	    s)
	      echo "Skipping user cin"
	      sq=1
	      ;;
	    c)
	      echo "Fowarding options $OPTARG to configure script"
	      configure_options=$OPTARG
	      ;;
	    h)  #show help
      	      HELP
              ;;
    	    \?) #unrecognized option - are fowarded to configure
              ;;
	esac
done

discover_os

## Remove old dependencies and installations

if [ x"$i_dir" == x" " ]; then
 i_dir="$HOME"
fi

remove_old $i_dir

## Check and try to install the prerequisites

pre_req

## clone the dependencies

git submodule init
if [ $? -ne 0 ]; then
  echo -e "Configure\033[91;5;1m FAILED \033[0m"
  exit 1
fi

git submodule update
if [ $? -ne 0 ]; then
  echo -e "Configure\033[91;5;1m FAILED \033[0m"
  exit 1
fi

# Create config directory in each submodule

cd openfpm_data
if [ ! -d src/config  ]; then
  mkdir src/config
fi
cd ..

cd openfpm_devices
if [ ! -d src/config  ]; then
  mkdir src/config
fi
cd ..

cd openfpm_vcluster
if [ ! -d src/config  ]; then
  mkdir src/config
fi
cd ..

cd openfpm_io
if [ ! -d src/config  ]; then
  mkdir src/config
fi
cd ..

cd openfpm_numerics
if [ ! -d src/config  ]; then
  mkdir src/config
fi
cd ..

# Create config directory

if [ ! -d src/config ]; then
  mkdir src/config
fi

## generate configure script

sh ./autogen.sh
if [ $? -ne 0 ]; then
  echo -e "Configure\033[91;5;1m FAILED \033[0m"
  exit 1
fi

## check for options

echo -e "\033[1;34;5mDEPENCENCIES INSTALLATION DIR      \033[0m"
echo -e "Every required dependencies if needed will be installed into: \033[1;34;5m$i_dir\033[0m"
echo -e "if you want to install somewhere else do ./install -i /somewhere/else"
if [ $sq -eq 0 ]; then
  unset commands
  commands[0]="Continue"
  possible_solutions "${commands[@]}"
fi

ncore=4
echo -e "\033[1mHow many core you want to use to install the dependencies?\033[0m"
if [ $sq -eq 0 ]; then
  read ncore
fi

echo -e "Installing requirements into: $i_dir "

##

## Take all the options with the exception of -d -i -s

## call the configure script

### Installing PETSC

if [ ! -d "$i_dir/PETSC" -o ! -d "$i_dir/EIGEN" ]; then
    echo -e "\033[1;34m Optional packages  \033[0m"
    echo -e "\033[1mDo you want to install linear algebra packages ?(y/n)\033[0m"
    echo "Installation can take long time (90 minutes on i7-3612QM 4 cores)"
    if [ $sq -eq 0 ]; then
      read inst_lin_alg
    else
      inst_lin_alg = n
    fi

#    if [ ! x"$choose" == x"0" ]; then
#        ./script/install_PETSC.sh $i_dir $choose
#        configure_options="$configure_options --with-PETSC=$i_dir/PETSC "
#    fi
fi

lin_alg_dir=""
lin_alg_lib=""
lin_alg_inc=""
if [ -d "$i_dir/PETSC" ]; then
    configure_options="$configure_options --with-petsc=$i_dir/PETSC "
    lin_alg_dir="$lin_alg_dir -L$i_dir/PETSC/lib"
    lin_alg_lib="$lin_alg_lib -lpetsc"
    lin_alg_inc="$lin_alg_inc -I$i_dir/PETSC/include"
fi
if [ -d "$i_dir/HYPRE" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/HYPRE/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/HYPRE/include"
fi
if [ -d "$i_dir/MUMPS" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/MUMPS/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/MUMPS/include"
fi
if [ -d "$i_dir/OPENBLAS" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/OPENBLAS/lib"
    lin_alg_lib="$lin_alg_lib -lopenblas"
    lin_alg_inc="$lin_alg_inc -I$i_dir/OPENBLAS/include"
    configure_blas_option="--with-blas=-L$i_dir/OPENBLAS/lib -lopenblas"
fi
if [ -d "$i_dir/SCALAPACK" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/SCALAPACK/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/SCALAPACK/include"
fi
if [ -d "$i_dir/SUPERLU_DIST" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/SUPERLU_DIST/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/SUPERLU_DIST/include"
fi
if [ -d "$i_dir/TRILINOS" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/TRILINOS/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/TRILINOS/include"
fi
if [ -d "$i_dir/SUITESPARSE" ]; then
    lin_alg_dir="$lin_alg_dir -L$i_dir/SUITESPARSE/lib"
    lin_alg_inc="$lin_alg_inc -I$i_dir/SUITESPARSE/include"
    lin_alg_lib="$lin_alg_lib -lumfpack -lamd -lbtf -lcamd -lccolamd -lcholmod -lcolamd -lcxsparse -lklu -ldl -lrbio -lspqr -lsuitesparseconfig"
    configure_options="$configure_options --with-suitesparse=$i_dir/SUITESPARSE "
fi
if [ -d "$i_dir/EIGEN" ]; then
    configure_options=" $configure_options --with-eigen=$i_dir/EIGEN "
    lin_alg_inc="$lin_alg_inc -I$i_dir/EIGEN"
fi
if [ -d "$i_dir/MPI" ]; then
    configure_options="$configure_options CXX=mpic++ "
fi
if [ -d "$i_dir/METIS" ]; then
    configure_options=" $configure_options --with-metis=$i_dir/METIS "
fi
if [ -d "$i_dir/BOOST" ]; then
    configure_options=" $configure_options --with-boost=$i_dir/BOOST "
fi
if [ -d "$i_dir/PARMETIS" ]; then
    configure_options=" $configure_options --with-parmetis=$i_dir/PARMETIS "
fi
if [ -d "$i_dir/HDF5" ]; then
    configure_options=" $configure_options --with-hdf5=$i_dir/HDF5/bin/h5pcc "
fi
if [ -d "$i_dir/LIBHILBERT" ]; then
    configure_options=" $configure_options --with-libhilbert=$i_dir/LIBHILBERT "
fi

### if we are on linux we have to add -rt

if [ x"$platform" = x"linux" ]; then
	lin_alg_lib="$lin_alg_lib -rt"
fi

### MPI

if [ x"$MPI_valid" == x"yes" ]; then
	configure_options="$configure_options CXX=mpic++ "
else
	./script/install_MPI.sh $i_dir $ncore
fi

### MPI compilers must be in your PATH folder

set_mpi $i_dir

### METIS and ParMETIS must be installed independently from sistem wide installation

./script/install_Parmetis.sh $i_dir $ncore
configure_options=" $configure_options --with-parmetis=$i_dir/PARMETIS "
./script/install_Metis.sh $i_dir $compiler_gcc $compiler_gpp $ncore
configure_options=" $configure_options --with-metis=$i_dir/METIS "

MPI_installed=0
MPI_System_prv=1
METIS_installed=1
PARMETIS_installed=1
BOOST_installed=0
BOOST_System_prv=1
LAPACK_installed=0
LAPACK_System_prv=1
SUITESPARSE_installed=0
SUITESPARSE_System_prv=1
EIGEN_installed=0
EIGEN_System_prv=1
HDF5_installed=0
HDF5_System_prv=1
LIBHILBERT_installed=0
conf_err=1

if [ $install_req -eq 0 ]; then
    ./configure $options $configure_options $configure_blas_option
else
    while [ $conf_err -ne 0 ]
    do
        ./configure $options $configure_options "$configure_blas_option"
        conf_err=$?

	echo "Configure script terminated with $conf_err"

        ## if MPI or METIS installation required install it
        if [ $conf_err -eq 200  ]; then
            echo "MPI not found try to install, $MPI_installed"
            if [ $MPI_installed -eq 1 ]; then
                echo "Error the installation of MPI failed"
                exit 1
            fi
            ./script/install_MPI.sh $i_dir $ncore
            MPI_installed=1
            export PATH="$PATH:$i_dir/MPI/bin"
            configure_options="$configure_options CXX=mpic++ "
        elif [ $conf_err -eq 201  ]; then
            echo "Metis not found try to install"
            if [ $METIS_installed -eq 1  ]; then
                echo "Error the installation of METIS failed"
                exit 1
            fi
            ./script/install_Metis.sh $i_dir $compiler_gcc $compiler_gpp
            METIS_installed=1
            configure_options=" $configure_options --with-metis=$i_dir/METIS "
        elif [ $conf_err -eq 202 ]; then
            echo "Boost not found try to install in $i_dir with $compiler_opt"
            if [ $BOOST_installed -eq 1  ]; then
                echo "Error the installation of Boost failed"
                exit 1
            fi
            ./script/install_BOOST.sh $i_dir $ncore
            BOOST_installed=1
            configure_options=" $configure_options --with-boost=$i_dir/BOOST "
	elif [ $conf_err -eq 208 ]; then
            echo "ParMetis not found try to install"
            if [ $PARMETIS_installed -eq 1  ]; then
                echo "Error the installation of ParMETIS failed"
                exit 1
            fi
            ./script/install_Parmetis.sh $i_dir $ncore
            PARMETIS_installed=1
            configure_options=" $configure_options --with-parmetis=$i_dir/PARMETIS "
        elif [ $conf_err -eq 207 ]; then
            echo "HDF5 not found try to install"
            if [ $HDF5_installed -eq 1 ]; then
                echo "Error the installation of HDF5 failed"
                exit 1	
            fi
            ./script/install_HDF5.sh $i_dir $ncore
            configure_options=" $configure_options --with-hdf5=$i_dir/HDF5/bin/h5pcc "
            HDF5_installed=1
        elif [ $conf_err -eq 210 ]; then
            echo "LIBHILBERT not found try to install"
            if [ $LIBHILBERT_installed -eq 1 ]; then
                echo "Error the installation of LIBHILBERT failed"
                exit 1
            fi
            ./script/install_LIBHILBERT.sh $i_dir $ncore
            configure_options=" $configure_options --with-libhilbert=$i_dir/LIBHILBERT "
            LIBHILBERT_installed=1
        elif [ $conf_err -ne 0 ]; then
            echo "I do not know how to recover from this error"
            exit 1
        fi
    done

    if [ x"$inst_lin_alg" == x"y" ]; then
        ./script/install_EIGEN.sh $i_dir $ncore
        if [ $? -eq 0 ]; then
            configure_options=" $configure_options --with-eigen=$i_dir/EIGEN --with-suitesparse=$i_dir/SUITESPARSE  "
            configure_blas_option=" --with-blas=\"$i_dir/OPENBLAS/lib -lopenblas\"  "
        fi
        ./script/install_PETSC.sh $i_dir $ncore
        if [ $? -eq 0 ]; then
            configure_options=" $configure_options --with-petsc=$i_dir/PETSC "
        fi
    fi

    ./configure $options $configure_options $configure_blas_option

fi

### Create example.mk
install_base=$(cat install_dir)
echo "INCLUDE_PATH=-I. -I$install_base/openfpm_numerics/include -I$install_base/openfpm_pdata/include/config -I$install_base/openfpm_pdata/include -I$install_base/openfpm_data/include -I$install_base/openfpm_vcluster/include -I$install_base/openfpm_io/include -I$install_base/openfpm_devices/include -I$i_dir/METIS/include -I$i_dir/PARMETIS/include -I$i_dir/BOOST/include -I$i_dir/HDF5/include -I$i_dir/LIBHILBERT/include  $lin_alg_inc" > example.mk
echo "LIBS_PATH= -L$install_base/openfpm_devices/lib -L$install_base/openfpm_pdata/lib  -L$install_base/openfpm_vcluster/lib -L$i_dir/METIS/lib -L$i_dir/PARMETIS/lib  -L$i_dir/BOOST/lib -L$i_dir/HDF5/lib -L$i_dir/LIBHILBERT/lib  $lin_alg_dir" >> example.mk
echo "LIBS=-lvcluster -lofpm_pdata -lofpmmemory -lparmetis -lmetis -lboost_iostreams -lhdf5 -llibhilbert  $lin_alg_lib" >> example.mk
echo "LIBS_SE2=-lvcluster -lofpmmemory_se2 -lparmetis -lmetis -lboost_iostreams -lhdf5 -llibhilbert $lin_alg_lib" >> example.mk
cp example.mk src/example.mk
cp example.mk example/example.mk

make clean
make

if [ $? -ne 0 ]; then
  conf_err=1
fi

echo "Command used to configure"
echo ""
echo -e "\033[1m ./configure $options $configure_options \033[0m "
echo ""

if [ x"$platform" = x"linux" ]; then
  bash_library="export LD_LIBRARY_PATH=\"\$LD_LIBRARY_PATH"
else
  bash_library="export DYLD_LIBRARY_PATH=\"\$DYLD_LIBRARY_PATH"
fi

bash_path="export PATH=\"\$PATH"

echo -e "\033[1;34;5m ---------------------------------------  \033[0m"
echo -e "\033[1;34;5m --------- INSTALLATION REPORT ---------  \033[0m"
echo ""
echo -e "\033[1;34;5m ---------- Mandatory packages ---------  \033[0m"
echo ""

if [ -d "$i_dir/MPI" ]; then
  installation_report="$installation_report \033[92;1mMPI\033[0m Installed: \033[1m $i_dir/MPI \033[0m\n"
  bash_path="$bash_path:$i_dir/MPI/bin"
  bash_library="$bash_library:$i_dir/MPI/lib"
elif [ $MPI_System_prv -eq 1 ]; then
  installation_report="$installation_report \033[92;1mMPI\033[0m Installed: \033[1m System installation \033[0m\n"
fi

if [ -d "$i_dir/METIS" ]; then
  installation_report="$installation_report \033[92;1mMETIS\033[0m Installed: \033[1m $i_dir/METIS \033[0m\n"
  bash_library="$bash_library:$i_dir/METIS/lib"
fi

if [ -d "$i_dir/PARMETIS" ]; then
  installation_report="$installation_report \033[92;1mPARMETIS\033[0m Installed: \033[1m $i_dir/PARMETIS \033[0m\n"
  bash_library="$bash_library:$i_dir/PARMETIS/lib"
fi

if [ -d "$i_dir/BOOST" ]; then
  installation_report="$installation_report \033[92;1mBOOST\033[0m Installed: \033[1m $i_dir/BOOST \033[0m\n"
  bash_library="$bash_library:$i_dir/BOOST/lib"
elif [ $BOOST_System_prv -eq 1 ]; then
  installation_report="$installation_report \033[92;1mBOOST\033[0m Installed: \033[1m System installation \033[0m\n"
fi

if [ -d "$i_dir/HDF5" ]; then
  installation_report="$installation_report \033[92;1mHDF5\033[0m Installed: \033[1m $i_dir/HDF5 \033[0m\n"
  bash_library="$bash_library:$i_dir/HDF5/lib"
fi

if [ -d "$i_dir/LIBHILBERT" ]; then
  installation_report="$installation_report \033[92;1mLibHilbert\033[0m Installed: \033[1m $i_dir/LIBHILBERT \033[0m\n"
  bash_library="$bash_library:$i_dir/LIBHILBERT/lib"
fi

echo -e "$installation_report"

echo ""
echo -e "\033[1;34;5m ---------- Optional packages -----------  \033[0m"
echo ""

installation_report=""

if [ -d "$i_dir/PETSC" ]; then
  installation_report="$installation_report \033[92;1mPETSC\033[0m Installed: \033[1m $i_dir/PETSC \033[0m\n"
  bash_library="$bash_library:$i_dir/PETSC/lib"
else
  installation_report="$installation_report \033[91;1mPETSC\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/EIGEN" ]; then
  installation_report="$installation_report \033[92;1mEIGEN\033[0m Installed: \033[1m $i_dir/EIGEN \033[0m\n"
fi

echo -e "$installation_report"

echo -e "\033[1;34;5m --------------------------------  \033[0m"

installation_report=""

if [ -d "$i_dir/TRILINOS" ]; then
  installation_report="$installation_report \033[92;1mTRILINOS\033[0m Installed: \033[1m $i_dir/TRILINOS \033[0m\n"
  bash_library="$bash_library:$i_dir/TRILINOS/lib"
else
  installation_report="$installation_report \033[91;1mTRILINOS\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/OPENBLAS" ]; then
  installation_report="$installation_report \033[92;1mOPENBLAS\033[0m Installed: \033[1m $i_dir/OPENBLAS \033[0m\n"
  bash_library="$bash_library:$i_dir/OPENBLAS/lib"
else
  installation_report="$installation_report \033[91;1mOPENBLAS\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/SUITESPARSE" ]; then
  installation_report="$installation_report \033[92;1mSUITESPARSE\033[0m Installed: \033[1m $i_dir/SUITESPARSE \033[0m\n"
  bash_library="$bash_library:$i_dir/SUITESPARSE/lib"
else
  installation_report="$installation_report \033[91;1mSUITESPARSE\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/SCALAPACK" ]; then
  installation_report="$installation_report \033[92;1mSCALAPACK\033[0m Installed: \033[1m $i_dir/SCALAPACK \033[0m\n"
  bash_library="$bash_library:$i_dir/SCALAPACK/lib"
else
  installation_report="$installation_report \033[91;1mSCALAPACK\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/MUMPS" ]; then
  installation_report="$installation_report \033[92;1mMUMPS\033[0m Installed: \033[1m $i_dir/MUMPS \033[0m\n"
  bash_library="$bash_library:$i_dir/MUMPS/lib"
else
  installation_report="$installation_report \033[91;1mMUMPS\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/SUPERLU_DIST" ]; then
  installation_report="$installation_report \033[92;1mSUPERLU_DIST\033[0m Installed: \033[1m $i_dir/SUPERLU_DIST \033[0m\n"
  bash_library="$bash_library:$i_dir/SUPERLU_DIST/lib"
else
  installation_report="$installation_report \033[91;1mSUPERLU_DIST\033[0m Installed: \033[1m NO \033[0m\n"
fi

if [ -d "$i_dir/HYPRE" ]; then
  installation_report="$installation_report \033[92;1mHYPRE\033[0m Installed: \033[1m $i_dir/HYPRE \033[0m\n"
  bash_library="$bash_library:$i_dir/HYPRE/lib"
else
  installation_report="$installation_report \033[91;1mHYPRE\033[0m Installed: \033[1m NO \033[0m\n"
fi

bash_path="$bash_path\""
bash_library="$bash_library\""

##### Writing openfpm_vars file

echo "$bash_path" > $HOME/openfpm_vars
echo "$bash_library" >> $HOME/openfpm_vars

echo -e "$installation_report"
echo ""
echo ""
if [ $conf_err -eq 0  ]; then
  echo -e "Install summary\033[92;5;1m SUCCEED \033[0m"
else
  echo -e "Install summary\033[91;5;1m FAILED \033[0m"
fi

echo ""
if [ x"$platform" = x"linux" ]; then
  echo "Before run any openfpm program you must execute the following command. A simple way would be to append this line at the end of your $HOME/.bashrc"
else
  echo "Before run any openfpm program you must execute the following command. A simple way would be to append this line at the end of your $HOME/.bash_profile"
fi
echo ""
echo -e "\033[1m source $HOME/openfpm_vars \033[0m"
echo ""
echo -e "\033[91;1m if you have in your .bashrc or .bash_profile old openfpm setting, please remove it\033[0m"
echo ""
echo ""
if [ $conf_err -ne 0 ]; then
  exit 1
fi
