#! /bin/bash

sed -i -e 's/home\/vagrant/usr\/local\/openfpm\/dependencies/g' /usr/local/openfpm/source/openfpm_vars
sed -i -e 's/home\/vagrant/usr\/local\/openfpm\/dependencies/g' /usr/local/openfpm/openfpm_pdata/include/example.mk
echo "export OPAL_PREFIX=/usr/local/openfpm/dependencies/MPI" >> /usr/local/openfpm/source/openfpm_vars


