#! /bin/bash

function discover_package_manager() {
  if [ x"$1" = x"osx" ]; then
    command -v brew >/dev/null
    if [ $? -eq 0 ]; then
      discover_package_manager_ret="brew"
      if [ ! -w /usr/local ]; then
        echo -e "\033[93;5mWARNING: \033[0m  /usr/local is not writtable, brew require that /usr/local is writtable and /usr/local/bin is in your PATH, otherwise the solutions with brew will fail"
        sleep 10
      fi
      return
    fi
    command -v port >/dev/null
    if [ command -v port >/dev/null 2>&1 ]; then
      discover_package_manager_ret="sudo port"
      return
    else
      discover_package_manager_ret=""
      return
    fi
  elif [ x"$1" = x"linux"  ]; then
    command -v yum >/dev/null
    if [ $? -eq 0 ]; then
      discover_package_manager_ret="yum"
      return
    fi
    command -v apt-get >/dev/null
    if [ $? -eq 0 ]; then
      discover_package_manager_ret="apt-get"
      return
    fi
    command -v zypper >/dev/null
    if [ $? -eq 0 ]; then
      discover_package_manager_ret="zypper"
      return
    else
      discover_package_manager_ret=""
      return
    fi
  fi
}

echo "$discover_package_manager_ret"

