#! /bin/bash

function set_mpi()
{
  if [ x"$MPI_valid" == x"yes" ]; then
        configure_options="$configure_options CXX=mpic++ "
  else
        ./script/install_MPI.sh $1 $2 $3 $4 $5 $6 $7
        MPI_installed=1
        export PATH="$1/MPI/bin:$PATH"
        configure_options="$configure_options CXX=mpic++ "
  fi

}

