#! /bin/bash

function possible_solutions {

   if [ $sq -eq 1 ]; then
     return
   fi

 sol=1
 echo "Possible solutions:"
 for com in "$@"
 do
   echo "$sol $com"
   sol=`expr $sol + 1`
 done
 echo "$sol exit the script"
 echo -e "\033[1;34;5mChoose the solution:\033[0m"
 read choose
 if [ x"$choose" = x"$sol" ]; then
  exit 1
 fi
 possible_solutions_ret=`expr $choose - 1`
 echo "Executing: ${command[$possible_solutions_ret]}"
 if [ -a input_install ]; then
   eval ${commands[$possible_solutions_ret]} < input_install
 else
   eval ${commands[$possible_solutions_ret]}
 fi
}

