#! /bin/bash 

function solve_gdbserver() {
source script/show_solutions
source script/discover_package_manager
discover_package_manager $1
pcman=$discover_package_manager_ret

if [ x"$pcman" = x"" ]; then
        exit 1
fi

if [ x"$1" = x"osx" ]; then
        commands[0]="$pcman install gdbserver"
        possible_solutions "${commands[@]}"
elif [ x"$1" = x"linux"  ]; then
	if [ x"$pcman" = x"zypper -n" ]; then
		package_name=gdbserver
	elif [ x"$pcman" = x"pacman" ]; then
		package_name=gdb
	elif [ x"$pcman" = x"apt-get" ]; then
		package_name=gdbserver
	else
		package_name=gdb-gdbserver
	fi

        pc_install_command "$pcman"
        commands[0]="su -c \"$pc_install_command_ret $package_name\""
        commands[1]="sudo $pc_install_command_ret $package_name"
        possible_solutions "${commands[@]}"
fi
}

