#! /bin/bash

function solve_gpp() {
source script/show_solutions
source script/discover_package_manager
discover_package_manager $1
pcman=$discover_package_manager_ret

if [ x"$pcman" = x"" ]; then
        exit 1
fi

if [ x"$1" = x"linux"  ]; then

	if [ x"$pcman" == x"pacman" ]; then
          commands[0]="su -c \"$pcman -Syu gcc make\""
          commands[1]="sudo $pcman -Syu gcc make mpfr"
          possible_solutions "${commands[@]}"
          compiler_gcc="gcc"
          compiler_gpp="g++"
        elif [ x"$pcman" == x"yum" -o x"$pcman" == x"zypper -n" ]; then
          commands[0]="su -c \"$pcman install gcc-c++\""
          commands[1]="sudo $pcman install gcc-c++"
          possible_solutions "${commands[@]}"
          compiler_gcc="gcc"
          compiler_gpp="g++"
        else
          commands[0]="su -c \"$pcman install g++\""
          commands[1]="sudo $pcman install g++"
          possible_solutions "${commands[@]}"
          compiler_gcc="gcc"
          compiler_gpp="g++"
        fi
elif [ x"$1" = x"msys"  ]; then
	if [ x"$pcman" == x"pacman" ]; then
          commands[0]="$pcman -Syu gcc make mpfr"
          possible_solutions "${commands[@]}"
          compiler_gcc="gcc"
          compiler_gpp="g++"
        fi

fi
}

