#! /bin/bash 

function solve_gfortran() {        
source script/show_solutions
source script/discover_package_manager
discover_package_manager $1
pcman=$discover_package_manager_ret

if [ x"$pcman" = x"" ]; then
        exit 1
fi

if [ x"$1" = x"osx" ]; then 
        commands[0]="$pcman install gcc"
        possible_solutions "${commands[@]}"
elif [ x"$1" = x"linux"  ]; then
	if [ x"$pcman" == x"pacman" ]; then
          commands[0]="su -c \"$pcman -Sy gcc-fortran\""
          commands[1]="sudo $pcman -Sy gcc-fortran"
          possible_solutions "${commands[@]}"
	elif [ x"$pcman" == x"zypper -n" ]; then
          commands[0]="su -c \"$pcman install gcc-fortran\""
          commands[1]="sudo $pcman install gcc-fortran"
          possible_solutions "${commands[@]}"
        elif [ x"$pcman" == x"apt-get" ]; then
          commands[0]="su -c \"$pcman install gfortran\""
          commands[1]="sudo $pcman install gfortran"
          possible_solutions "${commands[@]}"
        else
          commands[0]="su -c \"$pcman install gcc-gfortran\""
          commands[1]="sudo $pcman install gcc-gfortran"
          possible_solutions "${commands[@]}"
        fi
elif [ x"$1" = x"msys"  ]; then
	if [ x"$pcman" == x"pacman" ]; then
          commands[0]="$pcman -Sy gcc-fortran"
          possible_solutions "${commands[@]}"
	fi
fi 
}

