#! /bin/bash

function solve_nodejs() {
source script/show_solutions
source script/discover_package_manager
discover_package_manager $1
pcman=$discover_package_manager_ret

if [ x"$pcman" = x"" ]; then
        exit 1
fi

if [ x"$pcman" == x"zypper -n" ]; then
        base_pkg=nodejs10
else
        base_pkg=nodejs
fi

if [ x"$1" = x"linux"  ]; then
        pc_install_command "$pcman"
        commands[0]="su -c \"$pc_install_command_ret $base_pkg\""
        commands[1]="sudo $pc_install_command_ret $base_pkg"
        possible_solutions "${commands[@]}"
fi
}

