#! /bin/bash

source script/show_solutions
source script/discover_package_manager
discover_package_manager $1
pcman=$discover_package_manager_ret

if [ x"$pcman" = x"" ]; then
        exit 1
fi

if [ x"$1" = x"osx" ]; then
        commands[0]="$pcman install libtool"
        possible_solutions "${commands[@]}"
        echo "Executing: ${command[$possible_solutions_ret]}"
        eval ${commands[$possible_solutions_ret]}
elif [ x"$1" = x"linux"  ]; then
        commands[0]="su -c \"$pcman install libtool\""
        commands[1]="sudo $pcman install libtool"
        possible_solutions "${commands[@]}"
        echo "Executing: ${command[$possible_solutions_ret]}"
        eval ${commands[$possible_solutions_ret]}
fi

